services:
  validator:
    image: validator
    build:
      context: .
      dockerfile: Dockerfile.validator
    volumes:
      - credentials:/credentials
      - genesis:/genesis

volumes:
  # local volume where sequencer's credentials can persist
  credentials:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './credentials'
  # a temporary fs where the genesis hash is announced
  genesis:
    driver_opts:
      type: tmpfs
      device: tmpfs